[package]
name = "lightbulb"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6.1.0"
hex = "0.4.3"
sha2 = "0.10.8"
thiserror = "2.0.9"
tokio = {version = "1.42.0", features = ["full"]}
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite" ] }
